### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by k-kipruto** [the-mvm/the-mvm.github.io#12]
first m not a web developer  just a bit knowledge of web development. lately was trying to change the theme to dark and I was struggling a lot, anything can you do to make theming easy. Thanks for the awesome theme.

**Comment by amaynez** [comment]
That's a great idea, let me work on it to implement a dark theme.

**Comment by amaynez** [comment]
DONE:

To configure the dark theme just change the following variables in the _config.yml file:
```YAML
# Dark or light theme
mode: dark # light or dark (default is light)
logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg" # if you wish to have a different logo in your dark theme (if you wish to use the same logo, please copy the logo path from the regular logo.
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

```
