### ISSUE TITLE
Ability to swap Disqus for https://utteranc.es/

### ISSUE THREAD

**Issue by SimonDarksideJ** [the-mvm/the-mvm.github.io#36]
**Is your feature request related to a problem? Please describe.**
I've always used Disqus in the past for blogs, however of late disqus comments are getting full of spam and ads

**Describe the solution you'd like**
Would be great to either have an Utterances implementation, or highlight the areas to be able to swap disqus for utterances

**Describe alternatives you've considered**
Considered turning off comments, but not great

**Additional context**
https://ljvmiranda921.github.io/notebook/2021/03/26/migrating-from-disqus-to-utterances/

**Comment by TinyZzh** [comment]
see #33 has been merged.

**Comment by SimonDarksideJ** [comment]
Fantastic work @TinyZzh , any update on when the docs will be updated on how to configure it properly?

I've pulled the latest and merged it in to my pages blog (seems to look good so far), so next step is to update the utterances config

**Comment by SimonDarksideJ** [comment]
OK, found the issue and it does seem to be up and running now.  
The repo configuration needs "<Github username>/<repo name>" to work, so this is my working configuration now:

```
# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: SimonDarksideJ/comments.SimonDarksideJ.github.io # The GitHub repo URL.  https://utteranc.es/
  issue_term: issue # The GitHub issue label
  label: comments # The GitHub comments label
  theme: github-dark # The GitHub comment's there. e.g. github-dark
```
